### ISSUE TITLE
Best way to structure the library?

### ISSUE THREAD

**Issue by bobtiki** [bobtiki/letterboxd#2]
I’m not sure if the way I’m structuring this library is the sanest way. I’m thinking the other API endpoints would have similar modules with classes, like the Film one, but the way I’m calling it from the Letterboxd instance — each class would map to a function in the Letterboxd class — seems… not ideal?

I’m roughly translating [their Ruby example client](https://github.com/grantyb/letterboxd-api-example-ruby-client) into Python, but they have all of the endpoint methods split out into different files, and then imported into the single Letterboxd class, so in reality, it’s just one giant class. That didn’t seem the right way to do it in Python, but perhaps you have another view on it.

**Comment by pruicr** [comment]
This all seems fine to me. As the Letterboxd API is built out more on their end, some structure may need to change, but for now this works just fine.
